INSERT INTO BOOTSCORD_USER (USER_NAME, PASSWORD, EMAIL, DISPLAY_NAME) VALUES ('EMERALD', 'password', 'emerald@xmail.com', 'emeraldu');
INSERT INTO BOOTSCORD_USER (USER_NAME, PASSWORD, EMAIL, DISPLAY_NAME) VALUES ('majesicat', 'password', 'catlover@xmail.com', 'krys10nel');
INSERT INTO BOOTSCORD_USER (USER_NAME, PASSWORD, EMAIL, DISPLAY_NAME) VALUES ('LowOnMana', 'password', 'Low@xmail.com', 'edson');
INSERT INTO BOOTSCORD_USER (USER_NAME, PASSWORD, EMAIL, DISPLAY_NAME) VALUES ('chad_the_based', 'password', 'chad@xmail.com', 'chad');
INSERT INTO BOOTSCORD_USER (USER_NAME, PASSWORD, EMAIL, DISPLAY_NAME) VALUES ('Shion_Uzuki', 'password', 'bestwaifu@xmail.com', 'Shion');
INSERT INTO BOOTSCORD_USER (USER_NAME, PASSWORD, EMAIL, DISPLAY_NAME) VALUES ('KOS-MOS', 'password', 'vector@xmail.com', 'KOS-MOS');

INSERT INTO FRIENDSHIP (USER_ONE_ID, USER_TWO_ID, ACCEPTED) VALUES (1,2,FALSE);
INSERT INTO FRIENDSHIP (USER_ONE_ID, USER_TWO_ID, ACCEPTED) VALUES (1,3,FALSE);
INSERT INTO FRIENDSHIP (USER_ONE_ID, USER_TWO_ID, ACCEPTED) VALUES (1,4,FALSE);
INSERT INTO FRIENDSHIP (USER_ONE_ID, USER_TWO_ID, ACCEPTED) VALUES (1,5,FALSE);
INSERT INTO FRIENDSHIP (USER_ONE_ID, USER_TWO_ID, ACCEPTED) VALUES (2,3,FALSE);
INSERT INTO FRIENDSHIP (USER_ONE_ID, USER_TWO_ID, ACCEPTED) VALUES (2,6,FALSE);
INSERT INTO FRIENDSHIP (USER_ONE_ID, USER_TWO_ID, ACCEPTED) VALUES (2,4,FALSE);
INSERT INTO FRIENDSHIP (USER_ONE_ID, USER_TWO_ID, ACCEPTED) VALUES (5,6,FALSE);